# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JAVA CI Main
on:
  push:
    branches: [ main ]
jobs:
  openJDK_17_Deploy:
    runs-on: [ hyper ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 17 win64
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: 'jdkfile'
          jdkFile: "I:/libs/java/jdk-17.0.2/openjdk-17.0.2_windows-x64_bin.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven deploy
        run: |
          mvn deploy -T9000 -DskipTests

  openJDK_17_Test:
    runs-on: [ hyper ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 17 win64
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: 'jdkfile'
          jdkFile: "I:/libs/java/jdk-17.0.2/openjdk-17.0.2_windows-x64_bin.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven test
        run: |
          mvn install -T8

  zuluJDK_17_Test:
    runs-on: [ hyper ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 17 win64
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: 'jdkfile'
          jdkFile: "I:/libs/java/zulu-jdk17.0.4-17.36.13/zulu17.36.13-ca-jdk17.0.4-win_x64.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven test
        run: |
          mvn install -T8

  openJDK_18_Test:
    runs-on: [ hyper ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 18 win64
        uses: actions/setup-java@v2
        with:
          java-version: "18"
          distribution: 'jdkfile'
          jdkFile: "I:/libs/java/jdk-18.0.2/openjdk-18.0.2_windows-x64_bin.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven test
        run: |
          mvn install -T8

  zuluJDK_18_Test:
    runs-on: [ hyper ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 18 win64
        uses: actions/setup-java@v2
        with:
          java-version: "18"
          distribution: 'jdkfile'
          jdkFile: "I:/libs/java/zulu-jdk18.0.2-18.32.11/zulu18.32.11-ca-jdk18.0.2-win_x64.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven test
        run: |
          mvn install -T8